### ISSUE TITLE
Update to PureScript v0.15

### ISSUE THREAD

**Issue by andys8** [dnikolovv/purescriptify#2]
Hey, cool project. I noticed this project is using craco and the PureScript loader I published some time ago. In case you want to update to React v18 and the latest PureScript compiler v0.15 it should now be possible. I released changes yesterday. No need to if you don't want to update (now), just wanted to tell you about the release and offer help in case something wouldn't work.

https://www.npmjs.com/package/craco-purescript-loader

https://github.com/andys8/create-react-app-purescript/commit/3ae3fb26bcac0f91b7a6fc46334e56b4cf343a6e

**Comment by dnikolovv** [comment]
Hey Andy!

Thanks! I'll pick it up if I don't forget.
